### ISSUE TITLE
Module not found: Can't resolve 'better-sqlite3'

### ISSUE THREAD

**Issue by AdamQuadmon** [datopian/markdowndb#44] opened 2023-10-14 10:05 UTC
Running a NextJs app on a Turborepo gives Module not found issues from `knex`

`Module not found: Can't resolve 'better-sqlite3'`

adding `better-sqlite3` to package.json will keep asking for the next missing packages (tedious, mysql, mysql2, oracle, etc)

```
Import trace for requested module:
../../node_modules/.pnpm/knex@2.5.1_better-sqlite3@9.0.0_sqlite3@5.1.6/node_modules/knex/lib/dialects/index.js
../../node_modules/.pnpm/knex@2.5.1_better-sqlite3@9.0.0_sqlite3@5.1.6/node_modules/knex/lib/knex-builder/internal/config-resolver.js
../../node_modules/.pnpm/knex@2.5.1_better-sqlite3@9.0.0_sqlite3@5.1.6/node_modules/knex/lib/knex-builder/Knex.js
../../node_modules/.pnpm/knex@2.5.1_better-sqlite3@9.0.0_sqlite3@5.1.6/node_modules/knex/lib/index.js
../../node_modules/.pnpm/knex@2.5.1_better-sqlite3@9.0.0_sqlite3@5.1.6/node_modules/knex/knex.js
../../node_modules/.pnpm/mddb@0.3.0_better-sqlite3@9.0.0/node_modules/mddb/dist/src/lib/markdowndb.js
../../node_modules/.pnpm/mddb@0.3.0_better-sqlite3@9.0.0/node_modules/mddb/dist/src/index.js
./src/providers/markdowndb.ts
./src/app/page.tsx

**Comment by rufuspollock** [comment] 2023-10-17 09:36
@AdamQuadmon thanks for reporting - we'll look into this.

**Comment by rufuspollock** [comment] 2023-12-22 11:34
@mohamedsalem401 can you take a look and spend <= 2h to see if you have a sense of what issue is and how long to fix and then we can decide what to do further.

**Comment by mohamedsalem401** [comment] 2023-12-31 23:54
I can't reproduce it. @AdamQuadmon Can you provide more information about the issue and whether it was resolved?

**Comment by rufuspollock** [comment] 2024-01-01 23:07
@mohamedsalem401 let's close this as INVALID then with that comment.

**Comment by mohamedsalem401** [comment] 2024-01-01 23:12
INVALID. I tried it on different scenarios and I couldn't reproduce the issue.

**Closed by mohamedsalem401** 2024-01-01 23:12 UTC

**Comment by rufuspollock** [comment] 2024-01-03 18:35
@mohamedsalem401 perfect closing comment. Just add `invalid` label as well.
