### ISSUE TITLE
Test for 500+ files

### ISSUE THREAD

**Issue by olayway** [datopian/markdowndb#26] opened 2023-06-08 14:49 UTC
Aside: Probably in future we want a test of some kind - for now we could just open an issue about adding a test so we don't forget.

_Originally posted by @rufuspollock in https://github.com/datopian/markdowndb/issues/24#issuecomment-1579178901_

**Comment by rufuspollock** [comment] 2023-11-15 19:02
WONTFIX. At least for now. (not a priority atm)

**Closed by rufuspollock** 2023-11-15 19:02 UTC
Labels: wontfix

**Comment by dstengle** [comment] 2023-12-15 23:37
I think you need this due to the regression that has happened. I could have a go at writing it.
